#!/bin/bash
set -e

source $(dirname $0)/version

ARCH=${ARCH:-"amd64"}
if [ "$ARCH" = "amd64" ]; then
  SUFFIX=""
elif [ "$ARCH" = "arm64" ]; then
  SUFFIX="-arm64"
else
  echo "Unsupported architecture: $ARCH"
  exit 1
fi

cd $(dirname $0)/..

TAG=${TAG:-${VERSION}${SUFFIX}}
REPO=${REPO:-rancher}

if echo $TAG | grep -q dirty; then
    TAG=dev
fi

mkdir -p dist/artifacts

IMAGE=${REPO}/security-scan:${TAG}
DOCKERFILE=package/Dockerfile
if [ -e ${DOCKERFILE}${SUFFIX} ]; then
    DOCKERFILE=${DOCKERFILE}${SUFFIX}
fi

docker build -f ${DOCKERFILE} -t ${IMAGE} .
echo Built ${IMAGE}

